#!/usr/bin/env sh

# for testing we define vars locally
SHPLUG_DIR=./_shplug/
SHPLUG_SRC=./_shplug/src/
SHPLUG_BIN=./bin/
GIT_HOST="http://github.com"

log() {
    lvl="$1"; shift 1

    echo "$0:$lvl: $*" >&2
}

err() {
    log Err "$@"
}

have() {
    command -v "$1" >/dev/null
}

cursor() {
    case "$1" in
        up)
            printf "\\033[%sA" "$2" ;;
        down)
            printf "\\033[%sB" "$2" ;;
        home)
            printf "\\r" ;;
        clear)
            mode=2
            case "$2" in
                end) mode=0 ;;
                start) mode=1 ;;
                line) mode=2 ;;
            esac

            printf "\\033[%sK" "$mode";;
    esac
}

spinner() {
    frames='\|/-'
    while sleep 0.15; do
        frames=$(echo "$frames" | sed 's/\(.\)\(...\)/\2\1/')
        frame=$(echo "$frames" | cut -c1)

        printf "%s %s (%s)\\n" "$frame" "$1" "$2"
    done &
    pid=$!

    wait "$2"
    kill "$pid"
    wait "$pid" 2>/dev/null
}

clone() {
    cd "$SHPLUG_SRC" && git clone "$1" 1>&2 &
    if spinner "Cloning $1" $!; then
        echo "Done clone!"
        return 0
    else
        echo "Failed clone!"
        return 1
    fi
}

register() {
    mkdir -p "$SHPLUG_DIR"

    if ! [ -n "$1" ]; then
        err "missing git repository path!"
        exit 1
    else
        git_path="$GIT_HOST/$1"
        shift 1
    fi

    queue_entry="$git_path	&"

    touch "$SHPLUG_DIR/queue"
    echo "$queue_entry" >> "$SHPLUG_DIR/queue"
}

load() {
    rm -rf "$SHPLUG_DIR/tmp/"
    mkdir -p "$SHPLUG_SRC"
    mkdir -p "$SHPLUG_DIR/tmp/"

    queuefile="$SHPLUG_DIR/queue"
    logfile="$SHPLUG_DIR/log"
    touch "$queuefile"
    touch "$logfile"

    max_id=$(wc -l "$queuefile" | cut -d' ' -f1)

    for ii in $(seq 1 "$max_id"); do
        # eval "stat_$ii=PLACEHOLDER_$ii"
        # eval echo "\$stat_$ii"
        echo "PLACEHOLDER_$ii"
    done

    {
        id=
        i=0
        while read -r entry; do
            i=$((i+1))
            clone "$(echo "$entry" | cut -f1)" | sed -u "s/^/$i	/" 2>"$logfile" &
            pid=$!
            # {
            #     if wait $pid; then
            #         eval "exit_code_$i=0"
            #     fi
            # } &
        done < "$queuefile"
    } | {
        while read -r status; do
            id=$(echo "$status" | cut -d '	' -f1)
            status=$(echo "$status" | cut -d '	' -f2-)

            cur_stat=$(printf "%s/%s .... %s" "$id" "$max_id" "$status")
            # eval "stat_$id='$cur_stat'"

            lines_up=$((max_id + 1 - id))

            printf "%s" "$(
                cursor up $lines_up
                printf "%s" "$cur_stat"
                cursor clear end
                cursor home
                cursor down $lines_up
            )"
        done
    }

}

if [ "$1" = "load" ]; then
    if ! have git; then
        err "command: \`git\` is missing!"
        exit 1
    fi
    shift 1
    load "$*"
else
    register "$*"
fi





